// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {container} from '../models';

export function AddPoin(arg1:models.AddPoinRequest):Promise<models.Pelanggan>;

export function ApplyPromo(arg1:models.ApplyPromoRequest):Promise<models.ApplyPromoResponse>;

export function ChangePassword(arg1:models.ChangePasswordRequest):Promise<void>;

export function ClearKeranjang():Promise<void>;

export function CreateKategori(arg1:models.Kategori):Promise<void>;

export function CreatePelanggan(arg1:models.CreatePelangganRequest):Promise<models.Pelanggan>;

export function CreateProduk(arg1:models.Produk):Promise<void>;

export function CreatePromo(arg1:models.CreatePromoRequest):Promise<models.Promo>;

export function CreateReturn(arg1:models.CreateReturnRequest):Promise<void>;

export function CreateTransaksi(arg1:models.CreateTransaksiRequest):Promise<models.TransaksiResponse>;

export function CreateUser(arg1:models.CreateUserRequest):Promise<void>;

export function DebugPromoValidation(arg1:string,arg2:Array<models.TransaksiItemRequest>):Promise<string>;

export function DeleteExpiredBatch(arg1:string):Promise<void>;

export function DeleteKategori(arg1:number):Promise<void>;

export function DeletePelanggan(arg1:number):Promise<void>;

export function DeleteProduk(arg1:number):Promise<void>;

export function DeletePromo(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function DetectHardware():Promise<models.HardwareListResponse>;

export function GetActivePromos():Promise<Array<models.Promo>>;

export function GetAllBatches():Promise<Array<models.Batch>>;

export function GetAllKategori():Promise<Array<models.Kategori>>;

export function GetAllPelanggan():Promise<Array<models.Pelanggan>>;

export function GetAllProduk():Promise<Array<models.Produk>>;

export function GetAllPromo():Promise<Array<models.Promo>>;

export function GetAllReturn():Promise<Array<models.ReturnDetail>>;

export function GetAllReturns():Promise<Array<models.ReturnDetail>>;

export function GetAllStaff():Promise<Array<models.User>>;

export function GetAllStaffReports(arg1:string,arg2:string):Promise<Array<models.StaffReport>>;

export function GetAllStaffReportsWithTrend():Promise<Array<models.StaffReportWithTrend>>;

export function GetAllTransaksi(arg1:number,arg2:number):Promise<Array<models.Transaksi>>;

export function GetAllUsers():Promise<Array<models.User>>;

export function GetBatchByID(arg1:string):Promise<models.Batch>;

export function GetBatchSummary(arg1:number):Promise<Record<string, any>>;

export function GetBatchesByProduk(arg1:number):Promise<Array<models.Batch>>;

export function GetCategoryBreakdown(arg1:string,arg2:string):Promise<Array<models.CategoryBreakdownResponse>>;

export function GetComprehensiveSalesReport(arg1:string,arg2:string):Promise<models.ComprehensiveSalesReport>;

export function GetComprehensiveStaffReport():Promise<models.ComprehensiveStaffReport>;

export function GetDashboardCategoryChart():Promise<Record<string, any>>;

export function GetDashboardCompositionChart():Promise<Record<string, any>>;

export function GetDashboardData():Promise<models.DashboardData>;

export function GetDashboardSalesChart():Promise<models.DashboardSalesChartResponse>;

export function GetExpiringBatches(arg1:number):Promise<Array<models.Batch>>;

export function GetHourlySales(arg1:string,arg2:string):Promise<Array<models.HourlySalesResponse>>;

export function GetInstalledPrinters():Promise<Array<models.PrinterInfo>>;

export function GetKategoriByID(arg1:number):Promise<models.Kategori>;

export function GetKeranjang():Promise<Array<models.KeranjangItem>>;

export function GetMonthlyComparisonTrend():Promise<Record<string, any>>;

export function GetPaymentMethodBreakdown(arg1:string,arg2:string):Promise<Array<models.PaymentBreakdownResponse>>;

export function GetPelangganByID(arg1:number):Promise<models.Pelanggan>;

export function GetPelangganByTelepon(arg1:string):Promise<models.Pelanggan>;

export function GetPelangganByTipe(arg1:string):Promise<Array<models.Pelanggan>>;

export function GetPelangganWithStats(arg1:string):Promise<models.PelangganDetail>;

export function GetPoinSettings():Promise<models.PoinSettings>;

export function GetPrintSettings():Promise<models.PrintSettings>;

export function GetPromoByID(arg1:number):Promise<models.Promo>;

export function GetPromoByKode(arg1:string):Promise<models.Promo>;

export function GetPromoForProduct(arg1:number):Promise<Array<models.Promo>>;

export function GetPromoProducts(arg1:number):Promise<Array<models.Produk>>;

export function GetReturnByID(arg1:number):Promise<models.ReturnDetail>;

export function GetSalesByPeriodForChart(arg1:string):Promise<Record<string, any>>;

export function GetSalesInsights(arg1:string,arg2:string):Promise<models.SalesInsightsResponse>;

export function GetSalesTrend(arg1:string,arg2:string):Promise<Array<models.SalesTrendResponse>>;

export function GetShiftProductivity():Promise<Record<string, number>>;

export function GetStaffHistoricalData(arg1:number):Promise<models.StaffHistoricalData>;

export function GetStaffReport(arg1:number,arg2:string,arg3:string):Promise<models.StaffReport>;

export function GetStaffReportDetail(arg1:number,arg2:string,arg3:string):Promise<models.StaffReportDetailWithItems>;

export function GetStaffReportWithMonthlyTrend(arg1:number,arg2:string,arg3:string):Promise<models.StaffReportWithTrend>;

export function GetStaffReportWithTrend(arg1:number,arg2:string,arg3:string):Promise<models.StaffReportWithTrend>;

export function GetStaffShiftData(arg1:number,arg2:string,arg3:string):Promise<Record<string, Record<string, any>>>;

export function GetStokHistory(arg1:number):Promise<Array<models.StokHistory>>;

export function GetTodayStats():Promise<Record<string, any>>;

export function GetTopProducts(arg1:string,arg2:string,arg3:number):Promise<Array<models.TopProductsResponse>>;

export function GetTransaksiByDateRange(arg1:string,arg2:string):Promise<Array<models.Transaksi>>;

export function GetTransaksiByID(arg1:number):Promise<models.TransaksiDetail>;

export function GetTransaksiByNoTransaksi(arg1:string):Promise<models.TransaksiDetail>;

export function GetTransaksiByPelanggan(arg1:number):Promise<Array<models.Transaksi>>;

export function GetUserByID(arg1:number):Promise<models.User>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:models.LoginRequest):Promise<models.LoginResponse>;

export function PrintReceipt(arg1:models.PrintReceiptRequest):Promise<void>;

export function ProcessKeranjang():Promise<void>;

export function RemoveFromKeranjang(arg1:number):Promise<void>;

export function SavePrintSettings(arg1:models.PrintSettings):Promise<void>;

export function ScanBarcode(arg1:string,arg2:number):Promise<models.ScanBarcodeResponse>;

export function SetServices(arg1:container.ServiceContainer):Promise<void>;

export function TestCashDrawer(arg1:string):Promise<models.TestHardwareResponse>;

export function TestPrint(arg1:string):Promise<void>;

export function TestPrinter(arg1:string):Promise<models.TestHardwareResponse>;

export function TestScanner(arg1:string):Promise<models.TestHardwareResponse>;

export function UpdateBatchStatuses():Promise<void>;

export function UpdateKategori(arg1:models.Kategori):Promise<void>;

export function UpdateKeranjangJumlah(arg1:number,arg2:number):Promise<void>;

export function UpdatePelanggan(arg1:models.UpdatePelangganRequest):Promise<models.Pelanggan>;

export function UpdatePoinSettings(arg1:models.UpdatePoinSettingsRequest):Promise<models.PoinSettings>;

export function UpdateProduk(arg1:models.Produk):Promise<void>;

export function UpdatePromo(arg1:models.UpdatePromoRequest):Promise<models.Promo>;

export function UpdateStok(arg1:models.UpdateStokRequest):Promise<void>;

export function UpdateStokIncrement(arg1:models.UpdateStokRequest):Promise<void>;

export function UpdateUser(arg1:models.UpdateUserRequest):Promise<void>;
