// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPoin(arg1) {
  return window['go']['main']['App']['AddPoin'](arg1);
}

export function ApplyPromo(arg1) {
  return window['go']['main']['App']['ApplyPromo'](arg1);
}

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function ClearKeranjang() {
  return window['go']['main']['App']['ClearKeranjang']();
}

export function CreateKategori(arg1) {
  return window['go']['main']['App']['CreateKategori'](arg1);
}

export function CreatePelanggan(arg1) {
  return window['go']['main']['App']['CreatePelanggan'](arg1);
}

export function CreateProduk(arg1) {
  return window['go']['main']['App']['CreateProduk'](arg1);
}

export function CreatePromo(arg1) {
  return window['go']['main']['App']['CreatePromo'](arg1);
}

export function CreateReturn(arg1) {
  return window['go']['main']['App']['CreateReturn'](arg1);
}

export function CreateTransaksi(arg1) {
  return window['go']['main']['App']['CreateTransaksi'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DebugPromoValidation(arg1, arg2) {
  return window['go']['main']['App']['DebugPromoValidation'](arg1, arg2);
}

export function DeleteExpiredBatch(arg1) {
  return window['go']['main']['App']['DeleteExpiredBatch'](arg1);
}

export function DeleteKategori(arg1) {
  return window['go']['main']['App']['DeleteKategori'](arg1);
}

export function DeletePelanggan(arg1) {
  return window['go']['main']['App']['DeletePelanggan'](arg1);
}

export function DeleteProduk(arg1) {
  return window['go']['main']['App']['DeleteProduk'](arg1);
}

export function DeletePromo(arg1) {
  return window['go']['main']['App']['DeletePromo'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DetectHardware() {
  return window['go']['main']['App']['DetectHardware']();
}

export function GetActivePromos() {
  return window['go']['main']['App']['GetActivePromos']();
}

export function GetAllBatches() {
  return window['go']['main']['App']['GetAllBatches']();
}

export function GetAllKategori() {
  return window['go']['main']['App']['GetAllKategori']();
}

export function GetAllPelanggan() {
  return window['go']['main']['App']['GetAllPelanggan']();
}

export function GetAllProduk() {
  return window['go']['main']['App']['GetAllProduk']();
}

export function GetAllPromo() {
  return window['go']['main']['App']['GetAllPromo']();
}

export function GetAllReturn() {
  return window['go']['main']['App']['GetAllReturn']();
}

export function GetAllReturns() {
  return window['go']['main']['App']['GetAllReturns']();
}

export function GetAllStaff() {
  return window['go']['main']['App']['GetAllStaff']();
}

export function GetAllStaffReports(arg1, arg2) {
  return window['go']['main']['App']['GetAllStaffReports'](arg1, arg2);
}

export function GetAllStaffReportsWithTrend() {
  return window['go']['main']['App']['GetAllStaffReportsWithTrend']();
}

export function GetAllTransaksi(arg1, arg2) {
  return window['go']['main']['App']['GetAllTransaksi'](arg1, arg2);
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBatchByID(arg1) {
  return window['go']['main']['App']['GetBatchByID'](arg1);
}

export function GetBatchSummary(arg1) {
  return window['go']['main']['App']['GetBatchSummary'](arg1);
}

export function GetBatchesByProduk(arg1) {
  return window['go']['main']['App']['GetBatchesByProduk'](arg1);
}

export function GetCategoryBreakdown(arg1, arg2) {
  return window['go']['main']['App']['GetCategoryBreakdown'](arg1, arg2);
}

export function GetComprehensiveSalesReport(arg1, arg2) {
  return window['go']['main']['App']['GetComprehensiveSalesReport'](arg1, arg2);
}

export function GetComprehensiveStaffReport() {
  return window['go']['main']['App']['GetComprehensiveStaffReport']();
}

export function GetDashboardCategoryChart() {
  return window['go']['main']['App']['GetDashboardCategoryChart']();
}

export function GetDashboardCompositionChart() {
  return window['go']['main']['App']['GetDashboardCompositionChart']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDashboardSalesChart() {
  return window['go']['main']['App']['GetDashboardSalesChart']();
}

export function GetExpiringBatches(arg1) {
  return window['go']['main']['App']['GetExpiringBatches'](arg1);
}

export function GetHourlySales(arg1, arg2) {
  return window['go']['main']['App']['GetHourlySales'](arg1, arg2);
}

export function GetInstalledPrinters() {
  return window['go']['main']['App']['GetInstalledPrinters']();
}

export function GetKategoriByID(arg1) {
  return window['go']['main']['App']['GetKategoriByID'](arg1);
}

export function GetKeranjang() {
  return window['go']['main']['App']['GetKeranjang']();
}

export function GetMonthlyComparisonTrend() {
  return window['go']['main']['App']['GetMonthlyComparisonTrend']();
}

export function GetPaymentMethodBreakdown(arg1, arg2) {
  return window['go']['main']['App']['GetPaymentMethodBreakdown'](arg1, arg2);
}

export function GetPelangganByID(arg1) {
  return window['go']['main']['App']['GetPelangganByID'](arg1);
}

export function GetPelangganByTelepon(arg1) {
  return window['go']['main']['App']['GetPelangganByTelepon'](arg1);
}

export function GetPelangganByTipe(arg1) {
  return window['go']['main']['App']['GetPelangganByTipe'](arg1);
}

export function GetPelangganWithStats(arg1) {
  return window['go']['main']['App']['GetPelangganWithStats'](arg1);
}

export function GetPoinSettings() {
  return window['go']['main']['App']['GetPoinSettings']();
}

export function GetPrintSettings() {
  return window['go']['main']['App']['GetPrintSettings']();
}

export function GetPromoByID(arg1) {
  return window['go']['main']['App']['GetPromoByID'](arg1);
}

export function GetPromoByKode(arg1) {
  return window['go']['main']['App']['GetPromoByKode'](arg1);
}

export function GetPromoForProduct(arg1) {
  return window['go']['main']['App']['GetPromoForProduct'](arg1);
}

export function GetPromoProducts(arg1) {
  return window['go']['main']['App']['GetPromoProducts'](arg1);
}

export function GetReturnByID(arg1) {
  return window['go']['main']['App']['GetReturnByID'](arg1);
}

export function GetSalesByPeriodForChart(arg1) {
  return window['go']['main']['App']['GetSalesByPeriodForChart'](arg1);
}

export function GetSalesInsights(arg1, arg2) {
  return window['go']['main']['App']['GetSalesInsights'](arg1, arg2);
}

export function GetSalesTrend(arg1, arg2) {
  return window['go']['main']['App']['GetSalesTrend'](arg1, arg2);
}

export function GetShiftProductivity() {
  return window['go']['main']['App']['GetShiftProductivity']();
}

export function GetStaffHistoricalData(arg1) {
  return window['go']['main']['App']['GetStaffHistoricalData'](arg1);
}

export function GetStaffReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffReport'](arg1, arg2, arg3);
}

export function GetStaffReportDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffReportDetail'](arg1, arg2, arg3);
}

export function GetStaffReportWithMonthlyTrend(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffReportWithMonthlyTrend'](arg1, arg2, arg3);
}

export function GetStaffReportWithTrend(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffReportWithTrend'](arg1, arg2, arg3);
}

export function GetStaffShiftData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffShiftData'](arg1, arg2, arg3);
}

export function GetStokHistory(arg1) {
  return window['go']['main']['App']['GetStokHistory'](arg1);
}

export function GetTodayStats() {
  return window['go']['main']['App']['GetTodayStats']();
}

export function GetTopProducts(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopProducts'](arg1, arg2, arg3);
}

export function GetTransaksiByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetTransaksiByDateRange'](arg1, arg2);
}

export function GetTransaksiByID(arg1) {
  return window['go']['main']['App']['GetTransaksiByID'](arg1);
}

export function GetTransaksiByNoTransaksi(arg1) {
  return window['go']['main']['App']['GetTransaksiByNoTransaksi'](arg1);
}

export function GetTransaksiByPelanggan(arg1) {
  return window['go']['main']['App']['GetTransaksiByPelanggan'](arg1);
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function PrintReceipt(arg1) {
  return window['go']['main']['App']['PrintReceipt'](arg1);
}

export function ProcessKeranjang() {
  return window['go']['main']['App']['ProcessKeranjang']();
}

export function RemoveFromKeranjang(arg1) {
  return window['go']['main']['App']['RemoveFromKeranjang'](arg1);
}

export function SavePrintSettings(arg1) {
  return window['go']['main']['App']['SavePrintSettings'](arg1);
}

export function ScanBarcode(arg1, arg2) {
  return window['go']['main']['App']['ScanBarcode'](arg1, arg2);
}

export function SetServices(arg1) {
  return window['go']['main']['App']['SetServices'](arg1);
}

export function TestCashDrawer(arg1) {
  return window['go']['main']['App']['TestCashDrawer'](arg1);
}

export function TestPrint(arg1) {
  return window['go']['main']['App']['TestPrint'](arg1);
}

export function TestPrinter(arg1) {
  return window['go']['main']['App']['TestPrinter'](arg1);
}

export function TestScanner(arg1) {
  return window['go']['main']['App']['TestScanner'](arg1);
}

export function UpdateBatchStatuses() {
  return window['go']['main']['App']['UpdateBatchStatuses']();
}

export function UpdateKategori(arg1) {
  return window['go']['main']['App']['UpdateKategori'](arg1);
}

export function UpdateKeranjangJumlah(arg1, arg2) {
  return window['go']['main']['App']['UpdateKeranjangJumlah'](arg1, arg2);
}

export function UpdatePelanggan(arg1) {
  return window['go']['main']['App']['UpdatePelanggan'](arg1);
}

export function UpdatePoinSettings(arg1) {
  return window['go']['main']['App']['UpdatePoinSettings'](arg1);
}

export function UpdateProduk(arg1) {
  return window['go']['main']['App']['UpdateProduk'](arg1);
}

export function UpdatePromo(arg1) {
  return window['go']['main']['App']['UpdatePromo'](arg1);
}

export function UpdateStok(arg1) {
  return window['go']['main']['App']['UpdateStok'](arg1);
}

export function UpdateStokIncrement(arg1) {
  return window['go']['main']['App']['UpdateStokIncrement'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
